version: '3.8'
services:
  db:
    image: postgres:15
    container_name: v_exchange_postgres
    restart: always
    environment:
      POSTGRES_USER: vexchange
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: v_exchange
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 